CREATE OR REPALCE TABLE DEV_CONFIG.CICD_LOGS.TBL_CUSTOMER_DIM
(
CCUSTOMER_ID NUMBER
,CUSTOMER_NAME VARCHAR
,CREATED_TIMESTAMP TIMESTAMP_LTZ(6)
)
COMMENT = '{ "OBJECT_TYPE":"TABLE",
             "OBJECT_DETAILS" : {"DATABASE_NAME": "DEV_CONFIG", "SCHEMA_NAME":"CICD_LOGS","TABLE_NAME":"TBL_CUSTOMER_DIM"},
             "AUTHOR":"GMALIGE"
             ,"VERSION":"1.0"
             "JIRA_NUM":"SNOW-1000001"
             ,"DESCRIPTION": "Table to store Customer metadata"
             ,"CREATED_TIMESTAMP": "2022-05-30"}';